mercure:
    hubs:
        default:
            url: '%env(NEW_MERCURE_URL)%'
            public_url: '%env(NEW_MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
