old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost: '/'
    producers:
        send_chat_message:
            connection: default
            exchange_options:
                name: bot_answers
                type: direct
